# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Qq < Formula
  desc "A simple, fast job queue based on River Queue"
  homepage "https://github.com/willnewby/qq"
  version "0.1.10"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/willnewby/qq/releases/download/v0.1.10/qq_Darwin_x86_64.tar.gz"
      sha256 "1a23c918b1d85ce55019d64ffbaa8f93a9732e6affd3b2af5e670e7a6bf7ecc8"

      def install
        bin.install "qq"

        # Generate and install shell completions
        output = Utils.safe_popen_read("#{bin}/qq", "completion", "bash")
        (bash_completion/"qq").write output

        output = Utils.safe_popen_read("#{bin}/qq", "completion", "zsh")
        (zsh_completion/"_qq").write output

        output = Utils.safe_popen_read("#{bin}/qq", "completion", "fish")
        (fish_completion/"qq.fish").write output
      end
    end
    on_arm do
      url "https://github.com/willnewby/qq/releases/download/v0.1.10/qq_Darwin_arm64.tar.gz"
      sha256 "e8e6184c36819981ca98abfea17cfb3176c3f10de3e44ca66f99c544f5a9d96f"

      def install
        bin.install "qq"

        # Generate and install shell completions
        output = Utils.safe_popen_read("#{bin}/qq", "completion", "bash")
        (bash_completion/"qq").write output

        output = Utils.safe_popen_read("#{bin}/qq", "completion", "zsh")
        (zsh_completion/"_qq").write output

        output = Utils.safe_popen_read("#{bin}/qq", "completion", "fish")
        (fish_completion/"qq.fish").write output
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/willnewby/qq/releases/download/v0.1.10/qq_Linux_x86_64.tar.gz"
        sha256 "250631350328ee6346700644eecf7164d340b06ee5af57bc9778091171cc1082"

        def install
          bin.install "qq"

          # Generate and install shell completions
          output = Utils.safe_popen_read("#{bin}/qq", "completion", "bash")
          (bash_completion/"qq").write output

          output = Utils.safe_popen_read("#{bin}/qq", "completion", "zsh")
          (zsh_completion/"_qq").write output

          output = Utils.safe_popen_read("#{bin}/qq", "completion", "fish")
          (fish_completion/"qq.fish").write output
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/willnewby/qq/releases/download/v0.1.10/qq_Linux_arm64.tar.gz"
        sha256 "04f83ab68b83f002c803e6caa706db12127b4c6b82e1e9e1edeff32c66ad49bd"

        def install
          bin.install "qq"

          # Generate and install shell completions
          output = Utils.safe_popen_read("#{bin}/qq", "completion", "bash")
          (bash_completion/"qq").write output

          output = Utils.safe_popen_read("#{bin}/qq", "completion", "zsh")
          (zsh_completion/"_qq").write output

          output = Utils.safe_popen_read("#{bin}/qq", "completion", "fish")
          (fish_completion/"qq.fish").write output
        end
      end
    end
  end

  test do
    system "#{bin}/qq", "--version"
  end
end
