# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Qq < Formula
  desc "A simple, fast job queue based on River Queue"
  homepage "https://github.com/willnewby/qq"
  version "0.1.14"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/willnewby/qq/releases/download/v0.1.14/qq_Darwin_x86_64.tar.gz"
      sha256 "b457474f3765563c32323493cd6206eff38e3d4fcc3a8deef3d476f0a5654bb1"

      def install
        bin.install "qq"

        # Generate and install shell completions
        output = Utils.safe_popen_read("#{bin}/qq", "completion", "bash")
        (bash_completion/"qq").write output

        output = Utils.safe_popen_read("#{bin}/qq", "completion", "zsh")
        (zsh_completion/"_qq").write output

        output = Utils.safe_popen_read("#{bin}/qq", "completion", "fish")
        (fish_completion/"qq.fish").write output
      end
    end
    on_arm do
      url "https://github.com/willnewby/qq/releases/download/v0.1.14/qq_Darwin_arm64.tar.gz"
      sha256 "9e75a132adca748ccfd5035104b7755e2930f929f11969d3be24d04d5245cf75"

      def install
        bin.install "qq"

        # Generate and install shell completions
        output = Utils.safe_popen_read("#{bin}/qq", "completion", "bash")
        (bash_completion/"qq").write output

        output = Utils.safe_popen_read("#{bin}/qq", "completion", "zsh")
        (zsh_completion/"_qq").write output

        output = Utils.safe_popen_read("#{bin}/qq", "completion", "fish")
        (fish_completion/"qq.fish").write output
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/willnewby/qq/releases/download/v0.1.14/qq_Linux_x86_64.tar.gz"
        sha256 "b9827bebc0a049b0a1cbe6318a135d842f3f31d152252209b3fd7063d4817cac"

        def install
          bin.install "qq"

          # Generate and install shell completions
          output = Utils.safe_popen_read("#{bin}/qq", "completion", "bash")
          (bash_completion/"qq").write output

          output = Utils.safe_popen_read("#{bin}/qq", "completion", "zsh")
          (zsh_completion/"_qq").write output

          output = Utils.safe_popen_read("#{bin}/qq", "completion", "fish")
          (fish_completion/"qq.fish").write output
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/willnewby/qq/releases/download/v0.1.14/qq_Linux_arm64.tar.gz"
        sha256 "4d56e4e1fc67369a1e1d35b5114224dd3078a46685c288c0c06beaa8b507e946"

        def install
          bin.install "qq"

          # Generate and install shell completions
          output = Utils.safe_popen_read("#{bin}/qq", "completion", "bash")
          (bash_completion/"qq").write output

          output = Utils.safe_popen_read("#{bin}/qq", "completion", "zsh")
          (zsh_completion/"_qq").write output

          output = Utils.safe_popen_read("#{bin}/qq", "completion", "fish")
          (fish_completion/"qq.fish").write output
        end
      end
    end
  end

  test do
    system "#{bin}/qq", "--version"
  end
end
